Neos:
  Fusion:
    dsl:
      inline: Prgfx\Fusion\TemplateLiterals\Fusion\PlainTemplateLiterals
      plain: Prgfx\Fusion\TemplateLiterals\Fusion\ArrayRenderer
Prgfx:
  Fusion:
    TemplateLiterals:
      formatting:
        arrayRenderer:
          arrayPrototype: 'Neos.Fusion:Join'
          indentation: '    '
      blockDelimiters:
        default: ''
        block: '|'
        singleLine: '>'
        compress: '>>'
